### ISSUE TITLE
Some confusions about type (tag) taxonomy and mappings from entities to types

### ISSUE THREAD

**Issue by myexceptions** [xiaoling/figer#10]
As i converted the train.tar.gz to text data, i've found that the types are a bit noisy, e.g.,  
"LCD Soundsystem",
"/internet/social_network_user /broadcast/artist /music/artist /music/musical_group /common/topic".
There are some types not in the typeList in the research paper.

So, i wonder if there is a clear/specific mapping file, which maps entities exactly to some of the 112 types??

Anyway, i want to using the famous FIGER dataset in my experiments, so i have to pay attention to the details.

Thanks a lot!

**Comment by myexceptions** [comment]
Actually, i mean, when i use train.tar.gz, how do i know "/olympics/olympic_games" and "/soccer/football_world_cup" have been merged into Sports_Event.

**Comment by myexceptions** [comment]
oooooooh, the FIGER dataset is just the evolution set(test set) ?

And other experiments, which compared with FIGER, were trained on their own data?

Is that it? I just figure out.

**Comment by myexceptions** [comment]
i've found the file types.map.

**Comment by Alexisxsy** [comment]
Hi, I encounter the same problem. It seems that types.map has been removed as I cannot find it anywhere. I wonder if it is possible for you to show me the path or give me a copy? Thank you very much!
