### ISSUE TITLE
Absolute paths for testFile/outputFile cause problems

### ISSUE THREAD

**Issue by nschneid** [xiaoling/figer#2]
When I specify absolute paths for `testFile` and `outputFile` in the config file, each sentence with predicted mentions triggers a cryptic `sid not found` message and a NullPointerException, and is omitted from the output.

The workaround is to use a relative path. But a more informative error message, at least, would be helpful.

**Comment by xiaoling** [comment]
fixed (7691396). thanks for the feedback.  again sorry for the brittleness of the system. It may need some rework to make it more accessible.

**Comment by nschneid** [comment]
Hey, it's pretty good for research code. :) Thanks for releasing & improving it!
