### ISSUE TITLE
error: not found: value jetty

### ISSUE THREAD

**Issue by wazzy** [xiaoling/figer#3]
build.sbt:28: error: not found: value jetty
jetty()
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] Expected ID character
[error] Not a valid command: assembly
[error] assembly.sbt
[error]         ^

**Comment by xiaoling** [comment]
Thanks for reporting!

The issue comes from a deprecated version of xsbt-web-plugin. Fixed in 9119e2b.

**Comment by wazzy** [comment]
How can I train a new model and create "figer.new.model.gz".
How much training data is required to train model.
Can you please guide me to any reference or can you suggest me steps..

**Comment by xiaoling** [comment]
Please take a look at 56696ad. Some instructions are written on how to train a new model. But you need to use `entity.proto` to serialize the data.
