### ISSUE TITLE
Buidling train data from protobuf and while modeling it from trained data. Unable to do that.

### ISSUE THREAD

**Issue by nitinmlvya** [xiaoling/figer#5]
I want to build training data using protobuf. I explored entity.proto and reading the existing train.data file. I copied the single tagged sentence as it is and wrote a writer using protobuf and created train.data file. After that, I created model using that train.data file but I am unable to open. It gives Not a GZIP format.

I also want to know that how you create train.data using wikipedia data? Do you that code inside your git repository and where is it? 

I am attaching writer file and figer.conf file both . PFA for that and remind me, if I am doing anything wrong.

To support attached, I have renamed the files.
Renamed figer.conf to figer.txt -> [figer.txt](https://github.com/xiaoling/figer/files/41528/figer.txt)
Renamed WriteEntityFile.java to WriteEntityFile.txt -> [WriteEntityFile.txt](https://github.com/xiaoling/figer/files/41529/WriteEntityFile.txt)

**Comment by xiaoling** [comment]
I'm not sure I understand the issue. Are you able to get a model file? The training file doesn't have to be a gzip file. The code can handle both gzip and non-gzip files.

**Comment by nitinmlvya** [comment]
Thanks Xialong. I got it. I want to create my own training file rather than using train.tar.gz which you give. How can I create my own training file? What "Dependency" message means in "entity.proto" ?
Shall you help me? Thanks Again

**Comment by xiaoling** [comment]
@nitinmlvya  Sorry for the delay. Please take a look at [StanfordCoreNLP](http://stanfordnlp.github.io/CoreNLP/), which is the tool we use for syntactic analysis. Try using it on one of the sentences in the training set. Compare the output from StanfordCoreNLP with the fields in the protocol buffer file. It would be easy to see how they correspond.

[Make sure](http://stanfordnlp.github.io/CoreNLP/faq.html#how-can-i-get-original-stanford-dependencies-instead-of-universal-dependencies) that you use the Stanford Dependencies not the new universal ones.

**Comment by xiaoling** [comment]
closing due to lack of activities
