### ISSUE TITLE
The mapping from Wikipedia entities to Freebase Mids

### ISSUE THREAD

**Issue by yyaghoobzadeh** [xiaoling/figer#6]
Hi Xiao
I think for getting the types of Wikientities in the train.data, you had mapped them first to Freebase! 
I wounder if you can provide the mapping file that you've used for that, because I need to get back the Freebase MIDs of entities! (I have a mapping file myself but a lot of entities are not covered there)
I would appreciate if you help me. 
Thanks,
Yadollah

**Comment by xiaoling** [comment]
@yyaghoobzadeh Sorry for the delay. Let me clarify. You're asking for a mapping from wiki titles to freebase mids, right? For instance, a string like `https://en.wikipedia.org/wiki/Barack_Obama` will be mapped to `/m/02mjmr`.
Thanks, Xiao

**Comment by yyaghoobzadeh** [comment]
Now I am late!!
Basically yes, you have "entityName" in your EntityProto (like Barack_Obama) and I think you had mapped them to Freebase mid(/m/02mjmr) to find the Freebase types (and then mapped them to FIGER types). 
Thanks

**Comment by xiaoling** [comment]
Hey, 

Here is a file I dug up (https://drive.google.com/open?id=0B52yRXcdpG6MaHA5ZW9CZ21MbVk)

It's a mapping file from mids to wiki titles (gzipped tsv). Not sure that it has an 100% coverage. Hope it helps.

Thanks, Xiao

**Comment by yyaghoobzadeh** [comment]
Hi Xiao,
Thanks a lot! It should definitely help.

Best,
Yadollah

**Comment by gvishal** [comment]
It has 7611845 mid -> wiki mappings, FYI.

**Comment by sami001** [comment]
> Hey,
> 
> Here is a file I dug up (https://drive.google.com/open?id=0B52yRXcdpG6MaHA5ZW9CZ21MbVk)
> 
> It's a mapping file from mids to wiki titles (gzipped tsv). Not sure that it has an 100% coverage. Hope it helps.
> 
> Thanks, Xiao

Hi Xiao,
Can you tell us how did you find the mappings?
Thanks

**Comment by gloryVine** [comment]
> Hey,
> 
> Here is a file I dug up (https://drive.google.com/open?id=0B52yRXcdpG6MaHA5ZW9CZ21MbVk)
> 
> It's a mapping file from mids to wiki titles (gzipped tsv). Not sure that it has an 100% coverage. Hope it helps.
> 
> Thanks, Xiao

Hi, thank you.
Where did you find the file?
