### ISSUE TITLE
Research Publication GOLDEN Set

### ISSUE THREAD

**Issue by andybergon** [xiaoling/figer#8]
Is the file [exp.label](https://github.com/xiaoling/figer/blob/master/aaai/exp.label) containing the 434 sentences of the golden set used for the evaluation in the [research paper](http://xiaoling.github.io/pubs/ling-aaai12.pdf)?

What is the file [exp.out](https://github.com/xiaoling/figer/blob/master/aaai/exp.out) containing? The predictions of the FIGER model? If yes, why the sentences are a lot less than 434?

**Comment by xiaoling** [comment]
> Is the file exp.label containing the 434 sentences of the golden set used for the evaluation in the research paper?
yes, it is.

> What is the file exp.out containing? The predictions of the FIGER model? If yes, why the sentences are a lot less than 434?

The previous commit accidentally checked in a partial output. 1c47d3f updated the output file.
